connection_databricks:
  target: dev_local
  outputs:
    # dev local profile used for dbt development on local mashie with token access
    dev_local:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: "{{ env_var('DBT_CATALOG', 'learning_catalog') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_blueprint_dev') }}"
      threads: 1
